# Generated by Django 5.1.1 on 2024-09-26 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produits', '0002_remove_produit_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='quantite',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='produit',
            name='nom',
            field=models.CharField(max_length=255),
        ),
    ]
